export const MARKER_DATA: Record<
  string,
  {
    name: string;
    description: string;
    category: string;
    markerType: string;
    offset: [number, number, number];
    scale: number;
  }
> = {
  // Camping & Lodging
  Central: {
    name: "Central",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 2, 0],
    scale: 1,
  },
  Lil_Bottom: {
    name: "Lil Bottom",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, -0.5, 0],
    scale: 1,
  },
  North_Crook: {
    name: "North Crook",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [1, 0, -1],
    scale: 1,
  },
  Old_Growth_Forest: {
    name: "Old Growth Forest",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 1, 0],
    scale: 1,
  },
  Shady_Pines: {
    name: "Shady Pines",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 0, 0],
    scale: 1,
  },
  Stone_Circle: {
    name: "Stone Circle",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 2, 0],
    scale: 1,
  },
  The_Glen: {
    name: "The Glen",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 2, 0],
    scale: 1,
  },
  The_Overlook: {
    name: "The Overlook",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 1, 0],
    scale: 1,
  },
  The_View: {
    name: "The View",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 1, 0],
    scale: 1,
  },
  Big_Bottom: {
    name: "Big Bottom",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 0.5, 0],
    scale: 1,
  },
  High_Meadow: {
    name: "High Meadow",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [0, 2, 0],
    scale: 1,
  },
  Woods_Of_Mystery: {
    name: "Woods Of Mystery",
    description: "",
    category: "Camping & Lodging",
    markerType: "camping",
    offset: [-1, 1, 0],
    scale: 1,
  },
  Accessibility_Camping_Spot: {
    name: "Accessibility Camping Spot",
    description: "",
    category: "Camping & Lodging",
    markerType: "accessibility",
    offset: [0, 1, -0.5],
    scale: 1,
  },
  Accessibility_Camping_Spot001: {
    name: "Accessibility Camping Spot",
    description: "",
    category: "Camping & Lodging",
    markerType: "accessibility",
    offset: [0, 1, 0],
    scale: 1,
  },
  RV_Camping: {
    name: "RV Camping",
    description: "",
    category: "Camping & Lodging",
    markerType: "rv_camping",
    offset: [-1, 1.75, -2.5],
    scale: 1,
  },
  RV_Camping001: {
    name: "RV Camping",
    description: "",
    category: "Camping & Lodging",
    markerType: "rv_camping",
    offset: [1.75, 0.75, 7.5],
    scale: 1,
  },
  Car_Camping: {
    name: "Car Camping",
    description: "",
    category: "Camping & Lodging",
    markerType: "car_camping",
    offset: [-1, 0.5, -1],
    scale: 1,
  },
  Artist_Bunk: {
    name: "Artist Bunk",
    description: "",
    category: "Camping & Lodging",
    markerType: "artist_bunk",
    offset: [0, 2.5, -1],
    scale: 1,
  },
  QFF: {
    name: "QFF Camp",
    description: "",
    category: "Camping & Lodging",
    markerType: "qff",
    offset: [0, 2, 0],
    scale: 1,
  },

  // Ride Cher
  Big_Bottom_Drop: {
    name: "Big Bottom Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1.5, 1],
    scale: 0.75,
  },
  Circle_Drop: {
    name: "Circle Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1, 0],
    scale: 0.75,
  },
  Food_Court_Drop: {
    name: "Food Court Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1, 0],
    scale: 0.75,
  },
  Hemlock_Drop: {
    name: "Hemlock Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1, -0.25],
    scale: 0.75,
  },
  High_Meadow_Drop: {
    name: "High Meadow Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1, -0.5],
    scale: 0.75,
  },
  Large_Shower_Drop: {
    name: "Large Shower Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0.5, -1, -0.5],
    scale: 0.75,
  },
  Lil_Bottom_Drop: {
    name: "Lil Bottom Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1, -0.5],
    scale: 0.75,
  },
  North_Crook_Drop: {
    name: "North Crook Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1, 0],
    scale: 0.75,
  },
  Queeries_Drop: {
    name: "Queeries Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1.5, 0],
    scale: 0.75,
  },
  Rainbow_Bridge_Drop: {
    name: "Rainbow Bridge Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -1.5, -0.75],
    scale: 0.75,
  },
  Shady_Pines_Drop: {
    name: "Shady Pines Stop",
    description: `Our "Ride Cher" service is on hand to provide shuttle service within Main Camp for mobility impaired attendees who have picked up a wristband from our Wellness tent. If you need help getting around, grab a wristband and grab a ride!`,
    category: "Ride Cher",
    markerType: "cher_rides",
    offset: [0, -2, -1.5],
    scale: 0.75,
  },

  // Amenities
  Bar_1: {
    name: "Hemlock Hole Bar",
    description: "",
    category: "Amenities",
    markerType: "bar",
    offset: [0.5, 0.5, -0.25],
    scale: 0.75,
  },
  Bar_2: {
    name: "The Grove Bar",
    description: "",
    category: "Amenities",
    markerType: "bar",
    offset: [0.75, 0.25, -0.25],
    scale: 0.75,
  },
  Porta_Potties_1: {
    name: "Porta Potties - Hemlock Hole",
    description: "",
    category: "Amenities",
    markerType: "portapotties",
    offset: [0, 0, -0.3],
    scale: 0.5,
  },
  Porta_Potties_2: {
    name: "Porta Potties - The Grove",
    description: "",
    category: "Amenities",
    markerType: "portapotties",
    offset: [1, 0, 3.5],
    scale: 0.5,
  },
  Porta_Potties_3: {
    name: "Porta Potties - Old Growth Forest",
    description: "",
    category: "Amenities",
    markerType: "portapotties",
    offset: [0, -0.5, -0.25],
    scale: 0.5,
  },
  Porta_Potties_4: {
    name: "Porta Potties - Rainbow bridge",
    description: "",
    category: "Amenities",
    markerType: "portapotties",
    offset: [0, 0.75, -0.25],
    scale: 0.5,
  },
  Porta_Potties_4001: {
    name: "Porta Potties - High Meadow",
    description: "",
    category: "Amenities",
    markerType: "portapotties",
    offset: [0, 0.25, 0],
    scale: 0.5,
  },
  Wellness_1: {
    name: "Harm Reduction Tent - Main Camp",
    description: `Harm Reduction now has a dedicated location for you to do spectrometer testing on Wednesday & Thursday, reagent testing, and to pick up safer sex and safer usage kits.`,
    category: "Health & Wellness",
    markerType: "wellness",
    offset: [0.25, -0.25, -0.25],
    scale: 0.75,
  },
  Wellness_2: {
    name: "Harm Reduction Tent - New Camp",
    description: `Harm Reduction now has a dedicated location for you to do spectrometer testing on Wednesday & Thursday, reagent testing, and to pick up safer sex and safer usage kits.`,
    category: "Health & Wellness",
    markerType: "wellness",
    offset: [0.15, 0.35, -0.35],
    scale: 0.75,
  },
  Wellness_3: {
    name: "Wellness",
    description: `Wellness & Chill tents are staffed by medical professionals who are here to help. If you need first aid, charge on your CPAP, start to feel ill, or just need a breather from the chaos, find a Wellness Tent and communicate your needs to the staff.`,
    category: "Health & Wellness",
    markerType: "wellness",
    offset: [-0.15, -0.5, -0.15],
    scale: 0.75,
  },
  Chance_In_Sno: {
    name: "Chance InHell SnoBalls",
    description: `Icy treats for a world on fire! Born on a New Orleans porch during 2020 by queer married drag/burlesque duo Kitten N' Lou, Chance In Hell SnoBalls has a cult following as an obsession-worthy community hub.`,
    category: "Amenities",
    markerType: "chance_in_sno",
    offset: [0.5, 0.5, 0.15],
    scale: 0.75,
  },
  Food_Court: {
    name: "Food Court",
    description: `The Food Court is the place for Meal Plan holders to pick up their meals each day. Brunch hours are 9am-1pm, Dinner hours are 4-8pm. Limited A la Carte meals from the plan are sold at Pick-Me-Ups at the beginning of each meal period.`,
    category: "Amenities",
    markerType: "food_court",
    offset: [0, -0.25, -0.5],
    scale: 0.75,
  },
  Group_Shower: {
    name: "Group Shower",
    description: `Newly expanded group showers in New Camp. No tokens required.`,
    category: "Amenities",
    markerType: "group_shower",
    offset: [-0.5, 0, 0],
    scale: 0.75,
  },
  Kitchen: {
    name: "Kitchen",
    description: "",
    category: "Amenities",
    markerType: "kitchen",
    offset: [1.5, -0.5, -0.75],
    scale: 0.75,
  },
  Large_Shower: {
    name: "Large Shower",
    description: `Restrooms with flushing toilet stalls and sinks. \n Also featuring 8 private shower stalls requiring shower tokens.`,
    category: "Amenities",
    markerType: "large_shower",
    offset: [0, 0, -0.5],
    scale: 0.75,
  },
  Small_Shower: {
    name: "Small Shower",
    description: `Restrooms with flushing toilet stalls and sinks. \n Also featuring 2 private shower stalls and 4 group shower stalls requiring shower tokens.`,
    category: "Amenities",
    markerType: "small_shower",
    offset: [0.5, 0.25, 0.5],
    scale: 0.75,
  },
  Pick_Me_Up: {
    name: "Pick-Me-Ups!",
    description: `Pick-Me-Ups! is Honcho's curated Coffee & General shop stocked with everything you need from a la carte meals & snacks, to cocktails, other beverages, toiletries, ice, firewood and more. You can also charge your phone here.`,
    category: "Amenities",
    markerType: "pick_me_up",
    offset: [0, 0, 0],
    scale: 0.75,
  },
  Critters_Cafe: {
    name: "Critters Cafe",
    description: `Located just outside Critter's Lounge, this is New Camp's Coffee & Espresso Bar, also featuring à la Carte snacks, Specialty Drinks, late night food.`,
    category: "Amenities",
    markerType: "pick_me_up",
    offset: [0, -1.5, 0.25],
    scale: 0.75,
  },

  // Stages
  Circle_Of_Whispers: {
    name: "Circle Of Whispers",
    description: `Circle of Whispers is the home of both our Hearsay Speaker Series talks and our Mindfulness offerings. Throughout the day and night, programming here alternates between these two modalities.`,
    category: "Stages",
    markerType: "circle_of_whispers",
    offset: [0, -0.5, 0],
    scale: 1,
  },
  Critters_Lounge: {
    name: "Critters Lounge",
    description: `Critters Lounge is an anything-goes, fever dream of queer cabaret, drag, live music, and theatre. It takes place in a large circus tent at the top of The Great Meadow in New Camp. Imagine a cross between an after party for the carnies and a snake oil church revival, with an elevated cocktail bar built in.`,
    category: "Stages",
    markerType: "critters_lounge",
    offset: [0, 1, 0],
    scale: 1,
  },
  Hemlock_Hole: {
    name: "Hemlock Hole",
    description: `Located in Main Camp next to the swimming hole, Hemlock Hole runs for nearly 20 hours a day. By day, it's sunny & rowdy DJ sets, transitioning into "Hemlock Nights" late night on Friday and Saturday. Running until morning, these weekend sessions offer lower-BPM, melodic grooves curated as a chilled-out alternative to the high-energy club vibe of The Grove.`,
    category: "Stages",
    markerType: "hemlock_hole",
    offset: [1, 1, -0.5],
    scale: 1,
  },
  The_Grove: {
    name: "The Grove",
    description: `The Grove is our overnight, peak hour rave in New Camp's forest. From moody, opening set journeys, to nasty techno, electro, house, sunrise sets and magical festival closing moments on Sunday – this is the place to sweat.`,
    category: "Stages",
    markerType: "the_grove",
    offset: [0, 1, 0],
    scale: 1,
  },

  // Health & Wellness
  Sober_Space_Library: {
    name: "Library",
    description: `The Library is a new addition to Campout, acting as a "third space" for folks looking to relax and engage in queer community at a slower speed. It also serves as a Sober Space meetup location. You'll find all types of essential queer literature – from activism to afrofuturism, ecology, and even vintage porn mags. It also offers intimate once-daily talks, readings and workshops related to literature we'll have on hand.`,
    category: "Health & Wellness",
    markerType: "sober_space",
    offset: [0, -0.5, 0],
    scale: 0.75,
  },
  Sober_Space_Meadow: {
    name: "Sober Space - Meadow",
    description: `Sober folks, people in recovery, or anyone on the substance-free spectrum: check out the sober spaces for twice-daily meetings, mutual support, and bulletin boards to make connections. Enjoy your first or tenth sober Honcho! Meeting info is posted at both the sober spaces and Queeries. For more information, please reach out to chance.krempasky@gmail.com`,
    category: "Health & Wellness",
    markerType: "sober_space",
    offset: [-0.5, 0, 0.25],
    scale: 0.75,
  },
  Mail_Room: {
    name: "Mail Room",
    description: `Packages shipped to Main Camp can be picked up here. If you are camping in New Camp and marked this on your shipping label, your packages can be picked up at the New Camp Gate.`,
    category: "Health & Wellness",
    markerType: "mail_room",
    offset: [0, 2.5, 0],
    scale: 0.75,
  },
  Queeries001: {
    name: "Queeries",
    description: `Queeries is Campout's Help Desk. Have a general question, need help with your wristband, want to charge your phone, or have a public message to post on a board? Queeries is the spot.`,
    category: "Health & Wellness",
    markerType: "queeries.001",
    offset: [-0.25, -0.25, -0.25],
    scale: 0.75,
  },

  // Areas
  Main_Camp: {
    name: "Main Camp",
    description: "",
    category: "Areas",
    markerType: "main_camp",
    offset: [0, 1, 0],
    scale: 2.5,
  },
  New_Camp: {
    name: "New Camp",
    description: "",
    category: "Areas",
    markerType: "new_camp",
    offset: [0, 1, 0],
    scale: 2.5,
  },

  Gate_Main: {
    name: "Main Camp Gate",
    description: "",
    category: "Areas",
    markerType: "gate",
    offset: [0, 3, 0],
    scale: 2,
  },
  Gate_New: {
    name: "New Camp Gate",
    description: "",
    category: "Areas",
    markerType: "gate",
    offset: [0, 1.5, 0.2],
    scale: 2,
  },

  Parking_Main: {
    name: "Main Camp Parking",
    description: "",
    category: "Areas",
    markerType: "parking",
    offset: [0, 0.5, 0],
    scale: 1,
  },
  Parking_New: {
    name: "New Camp Parking",
    description: "",
    category: "Areas",
    markerType: "parking",
    offset: [0, 2, 0],
    scale: 1,
  },
  Salvage: {
    name: "Dumpsters & Salvage",
    description: "",
    category: "Areas",
    markerType: "salvage",
    offset: [0, -0.5, 0],
    scale: 0.75,
  },
};
